### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by adityavarma1234**
Fixed spelling of horizontal due to which the test layout _main_horizontal_4_panes.yml
 was not running.

### CODE REVIEW

**Comment by adityavarma1234** [comment]
@TomAnthony  have a look at this.

**Comment by adityavarma1234** [comment]
@TomAnthony

**Comment by TomAnthony** [comment]
Thanks for this! :)

**Comment by adityavarma1234** [comment]
Cool. Thanks. ☺

On Thu, Dec 31, 2015 at 12:20 AM, Tom Anthony <notifications@github.com>
wrote:

> Merged #17 <https://github.com/TomAnthony/itermocil/pull/17>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TomAnthony/itermocil/pull/17#event-502981887>.
>



-- 
Aditya Varma.
Mobile : 07899077460
SkypeId: varmaaditya

**Comment by adityavarma1234** [comment]
Will contribute MORE when I find TIME. :)

On Fri, Jan 1, 2016 at 8:06 PM, Aditya Varma <nitbaditya@gmail.com> wrote:

> Cool. Thanks. ☺
>
> On Thu, Dec 31, 2015 at 12:20 AM, Tom Anthony <notifications@github.com>
> wrote:
>
>> Merged #17 <https://github.com/TomAnthony/itermocil/pull/17>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/TomAnthony/itermocil/pull/17#event-502981887>.
>>
>
>
>
> --
> Aditya Varma.
> Mobile : 07899077460
> SkypeId: varmaaditya
>



-- 
Aditya Varma.
Mobile : 07899077460
SkypeId: varmaaditya

**Pull request merged**
